# Descriptive Statistics

**Module 2: Data Visualization** | Lean Six Sigma Data Analytics

---

## The Starting Point

Any data analysis starts by looking at **descriptive statistics**—summarizing your data in just a few key figures before diving into deeper analysis.

> It doesn't make sense to read aloud all 40 measurements. Instead, summarize values into key figures.

**Important:** Descriptive statistics only apply to **numerical data** because they're based on mathematical operations.

In [1]:
# Setup
import pandas as pd
import numpy as np

# --- Minitab-style house style -------------------------------------------
import sys
from pathlib import Path as _Path

# minitab_style.py lives in the parent folder of each module directory
sys.path.append(str(_Path.cwd().parent))
import minitab_style as ms

ms.apply_style()

DATA_FILE = '../data/da-lss.xlsx'
xlsx = pd.ExcelFile(DATA_FILE)
print('Data loaded successfully!')

Data loaded successfully!

---

## Example: Coffee Caffeine Content

**Context:** You produce coffee and want to sell it as decaf. If caffeine percentage is below 0.1%, the batch qualifies as decaf.

**Data:** 40 batches measured for caffeine percentage.

**Question:** How well does the production process perform? Are we producing decaf coffee?

In [2]:
# Load Caffeine batches data
caffeine = pd.read_excel(xlsx, sheet_name='Caffeine_batches', skiprows=6, usecols=[0, 1])
caffeine.columns = ['Batch', 'Caffeine_Pct']
caffeine = caffeine.dropna()

print(f'Dataset: {caffeine.shape[0]} batches\n')
caffeine.head(10)

Dataset: 40 batches

         Batch  Caffeine_Pct
0  082002-C116         0.092
1  082002-C122         0.105
2  082002-C126         0.079
3  082002-C141         0.118
4  082002-C147         0.069
5  082002-C166         0.096
6  082002-C168         0.069
7  082002-C171         0.080
8  082002-C188         0.074
9  092002-C376         0.093

---

## Two Categories of Descriptive Statistics

| Category | Measures | What It Tells You |
|----------|----------|-------------------|
| **Location** | Mean, Median | Where the data is centered |
| **Dispersion** | Standard Deviation, Variance, Range, IQR | How spread out the data is |

In [3]:
# Quick summary using pandas describe()
# Equivalent to Minitab: Stat > Basic Statistics > Display Descriptive Statistics
caffeine['Caffeine_Pct'].describe()

count    40.000000
mean      0.083175
std       0.016361
min       0.044000
25%       0.072750
50%       0.084500
75%       0.094000
max       0.118000
Name: Caffeine_Pct, dtype: float64

In [4]:
# Full descriptive statistics matching Minitab output
data = caffeine['Caffeine_Pct']

descriptive_stats = {
    'N': data.count(),
    'N* (missing)': data.isna().sum(),
    'Mean': data.mean(),
    'StDev': data.std(),
    'Variance': data.var(),
    'Minimum': data.min(),
    'Q1 (25th pctl)': data.quantile(0.25),
    'Median': data.median(),
    'Q3 (75th pctl)': data.quantile(0.75),
    'Maximum': data.max(),
    'Range': data.max() - data.min(),
    'IQR': data.quantile(0.75) - data.quantile(0.25)
}

stats_df = pd.DataFrame.from_dict(descriptive_stats, orient='index', columns=['Value'])
stats_df.round(6)

                    Value
N               40.000000
N* (missing)     0.000000
Mean             0.083175
StDev            0.016361
Variance         0.000268
Minimum          0.044000
Q1 (25th pctl)   0.072750
Median           0.084500
Q3 (75th pctl)   0.094000
Maximum          0.118000
Range            0.074000
IQR              0.021250

---

## Location Measures

### Mean (Average)

**Formula:** Sum of all measurements ÷ N

The mean indicates where your data is centered on the scale.

### Median

The value that separates the smallest 50% from the largest 50% when data is ordered.

| Measure | Advantage | Disadvantage |
|---------|-----------|--------------|
| Mean | Uses all data points; more precise | Affected by outliers |
| Median | Not affected by outliers | Only uses middle value; less precise |

In [5]:
print('Location Measures:')
print(f'  Mean:   {data.mean():.4f}%')
print(f'  Median: {data.median():.4f}%')
print()
print(f'Mean and median are close, suggesting symmetric distribution.')

Location Measures:
  Mean:   0.0832%
  Median: 0.0845%

Mean and median are close, suggesting symmetric distribution.

---

## Dispersion Measures

### Understanding Variation

Two datasets can have the same mean but very different spreads:
- **Low dispersion:** Values cluster close to the mean
- **High dispersion:** Values spread far from the mean

### Standard Deviation

**The Problem:** If we average the distances from each point to the mean, positives and negatives cancel out (≈ 0).

**The Solution:**
1. Square each distance (makes all values positive)
2. Average the squared distances = **Variance**
3. Take the square root = **Standard Deviation**

### Range vs IQR

| Measure | Formula | Robustness |
|---------|---------|------------|
| Range | Max − Min | Sensitive to outliers |
| IQR | Q3 − Q1 | Ignores extreme 25% on each end |

In [6]:
print('Dispersion Measures:')
print(f'  Std Dev:  {data.std():.4f}%')
print(f'  Variance: {data.var():.6f}')
print(f'  Range:    {data.max() - data.min():.4f}%')
print(f'  IQR:      {data.quantile(0.75) - data.quantile(0.25):.4f}%')
print()
print(f'Interpretation: Observations are, on average, {data.std():.4f}% away from the mean.')

Dispersion Measures:
  Std Dev:  0.0164%
  Variance: 0.000268
  Range:    0.0740%
  IQR:      0.0213%

Interpretation: Observations are, on average, 0.0164% away from the mean.

---

## Quartiles Explained

When data is ordered from small to large:

| Quartile | Definition |
|----------|------------|
| Q1 (25th percentile) | Separates lowest 25% from highest 75% |
| Median (50th percentile) | Separates lowest 50% from highest 50% |
| Q3 (75th percentile) | Separates lowest 75% from highest 25% |

In [7]:
print('Quartiles:')
print(f'  Q1 (25%): {data.quantile(0.25):.4f}% - 25% of batches below this')
print(f'  Median:   {data.median():.4f}% - 50% of batches below this')
print(f'  Q3 (75%): {data.quantile(0.75):.4f}% - 75% of batches below this')

Quartiles:

  Q1 (25%): 0.0727% - 25% of batches below this
  Median:   0.0845% - 50% of batches below this
  Q3 (75%): 0.0940% - 75% of batches below this

---

## Interpreting the Results

Now let's answer our business question: **Are we producing decaf coffee?**

In [8]:
threshold = 0.1  # Decaf threshold

print('Business Interpretation')
print('=' * 50)
print(f'Decaf threshold: {threshold}%')
print()
print(f'Mean caffeine:    {data.mean():.4f}% - {"BELOW" if data.mean() < threshold else "ABOVE"} threshold')
print(f'Maximum caffeine: {data.max():.4f}% - {"BELOW" if data.max() < threshold else "ABOVE"} threshold')
print()

failing = (data > threshold).sum()
print(f'Batches exceeding threshold: {failing} out of {len(data)}')
print(f'Failure rate: {(data > threshold).mean() * 100:.1f}%')
print()
print('Conclusion:')
if data.mean() < threshold and failing == 0:
    print('  All batches qualify as decaf.')
elif data.mean() < threshold:
    print('  On average, coffee is decaf, but some batches fail.')
    print('  High dispersion is causing quality issues.')
else:
    print('  Average caffeine exceeds threshold - process needs improvement.')

Business Interpretation
==================================================
Decaf threshold: 0.1%

Mean caffeine:    0.0832% - BELOW threshold
Maximum caffeine: 0.1180% - ABOVE threshold

Batches exceeding threshold: 5 out of 40
Failure rate: 12.5%

Conclusion:
  On average, coffee is decaf, but some batches fail.
  High dispersion is causing quality issues.

---

## Python Quick Reference

| Statistic | Python Code |
|-----------|-------------|
| Mean | `df['col'].mean()` |
| Median | `df['col'].median()` |
| Std Dev | `df['col'].std()` |
| Variance | `df['col'].var()` |
| Min/Max | `df['col'].min()`, `df['col'].max()` |
| Quartiles | `df['col'].quantile(0.25)`, `df['col'].quantile(0.75)` |
| Count | `df['col'].count()` |
| Missing | `df['col'].isna().sum()` |

---

## Key Takeaways

- **Descriptive statistics** summarize data into key figures before deeper analysis
- Only applicable to **numerical data**
- **Location measures:** Mean (uses all data, affected by outliers) and Median (robust)
- **Dispersion measures:** Std Dev/Variance (average distance from mean), Range/IQR (spread)
- **IQR** is more robust than range because it ignores extreme values
- Always examine both location AND dispersion to understand your data